Added Translations for Basket, Order, Tool, Product
relativityhd/CCT pull request #26
Opened 2020-10-23 11:37 UTC by ChristopherLohse

2020-10-23 17:16 UTC, relativityhd commented on frontend/src/locales/Basket/de.json
> +  }
End of file fehlt. EoF sind wichtig, hat weit zurück liegende Gründe. Einfach eine leere Zeile am Ende einer Datei einfügen.

2020-10-23 17:17 UTC, relativityhd commented on frontend/package.json
> +    "vuex-persist": "^3.1.3"
Bitte rückgängig machen, wird in einem anderem Branch gefixt. Sonst gibt es Merge-Konflikte.

2020-10-23 17:18 UTC, relativityhd commented on frontend/package.json
> +    "vuex-persist": "^3.1.3"
Außerdem package-lock changes komplett rückgängig machen

2020-10-23 17:19 UTC, relativityhd commented on frontend/src/locales/Basket/fr.json
> +  }
EoF missing

2020-10-23 17:45 UTC, ShirkahnW requested changes
Du brauchst noch eine File, die die generellen Sachen Übersetzt, da diese auch in dem Teil vorkommen. 
In tool/en.json ist die Übersetzung für "notEditable" grammatikalisch nicht korrekt.
Bitte mache im Englischen die Groß- und Kleinschreibung einheitlich

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/de.json
> +    "deleteItem": "Lösche Artikel aus deinem Einkaufswagen",
Lösche den Artikel

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/de.json
> +    "notCustom": "Dieser Artikel wurde nich individualisiertd",
nicht individualisiert

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/de.json
> +    "show": "Zeige vollständige Kalkulation",
Unschön. entweder: "Preiskalkulation zeigen" oder "Vollständige Kalkulation"

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/de.json
> +      "about": "Artikelinfo"
Unschön: Artikelinformationen

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/de.json
> +      "customize": "Individuzalisiere",
Ohne z

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/de.json
> +      "pricing": "Zeige kalkulation"
Kalkulation groß

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/fr.json
> +    "noItems": "YVotre panier est vide !",
Ohne Y

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/fr.json
> +    "notCustom": "ThiCe point n'a pas été personnalisés",
Cet point n'a pas été personnalisés

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/de.json
> +      "phone": "Telfon",
Telefon

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/de.json
> +      "city": "Bitte gib deinen Wohnort an!",
Bitte Konsequent ein oder an nutzen

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/de.json
> +      "phone": "Bitte gib eine gültige Telefonnumer an!",
Telefonnummer

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/de.json
> +    "failed": "Couldn't order stuff :(",
Fehlende Übersetzung

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/de.json
> +    "address": "Addresse",
Adresse

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/fr.json
> +    "failed": "Couldn't order stuff :(",
Fehlende Übersetzung

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/it.json
> +      "phone": "Si prega di inserire un numero di telefono valido!",
Bitte gleiche Satzstruktur verwenden

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Order/it.json
> +    "failed": "Couldn't order stuff :(",
Fehlende Übersetzung

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Product/de.json
> +    "addToCart": "In Einkaufswagen",
In den Einkaufswagen

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Product/de.json
> +    "notEditable": "Diese Artikelkombination lässt sich nich anpassenn"
nicht anpassen

2020-10-23 17:45 UTC, ShirkahnW commented on frontend/src/locales/Basket/fr.json
> +      "about": "Point Info"
Info klein

2020-10-24 10:55 UTC, ShirkahnW approved these changes

2020-10-24 10:55 UTC, merged